### ISSUE TITLE
Windows CUDA 12.6.0 not copied from `cf-staging` to `conda-forge`?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cuda-visual-tools-feedstock#14]
Recently we built packages for `cuda-visual-tools`. All builds ran successfully. All added packages to `cf-staging`. However all but the Windows package were copied

Here is [the CI log for the Windows package]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=993747&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=6119ccbe-9301-594f-7c27-f792b80a7fcc&l=756  ). At the end it seems to indicate the copy was successful

```json
copy results:
{
  "errors": [],
  "valid": {
    "win-64/cuda-visual-tools-12.6.0-h57928b3_0.conda": true
  },
  "copied": {
    "win-64/cuda-visual-tools-12.6.0-h57928b3_0.conda": true
  }
}
```

While we do see the package on `cf-staging` 

<img width="1840" alt="Screenshot 2024-08-02 at 1 41 15 PM" src="https://github.com/user-attachments/assets/ead58da0-5158-48cd-a0fe-8f51f3c1df42">

It is missing on `conda-forge`

<img width="1840" alt="Screenshot 2024-08-02 at 1 41 55 PM" src="https://github.com/user-attachments/assets/1cefe968-5593-47e6-8a44-992f2eb77e8c">

**Comment by jakirkham** [comment]
@beckermr does anything here stick out to you?

**Comment by beckermr** [comment]
nothing - i'd retry and we can debug more if it fails again

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

Gotcha yeah was thinking this could be an issue on the Anaconda.org side, but would think we get some HTTP error back

Alright will restart CI

Edit: Here are [the new CI jobs]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=993853&view=results )

**Comment by jakirkham** [comment]
Am seeing lines like this in the log. Is there anything else we need to do?

```
Distribution D:\bld\win-64\cuda-visual-tools-12.6.0-h57928b3_0.conda already exists on cf-staging. Waiting another 15 seconds to try uploading again.
Distribution D:\bld\win-64\cuda-visual-tools-12.6.0-h57928b3_0.conda already exists on cf-staging. Waiting another 30 seconds to try uploading again.
Distribution D:\bld\win-64\cuda-visual-tools-12.6.0-h57928b3_0.conda already exists on cf-staging. Waiting another 45 seconds to try uploading again.
```

Or will this resolve itself?

**Comment by jakirkham** [comment]
Nvm looks like it completed and now see the package uploaded

<img width="1840" alt="Screenshot 2024-08-02 at 2 16 58 PM" src="https://github.com/user-attachments/assets/f46f193b-859e-44ae-a0a6-f83e8b6d670e">

Closing as resolved
