### ISSUE TITLE
Is nsight compute really needed?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/cuda-visual-tools-feedstock#8]
https://github.com/conda-forge/cuda-visual-tools-feedstock/blob/b04239f788b57106e4809bbb0cf71a89646fe8fa/recipe/meta.yaml#L18C7-L18C21

It depends on qt-main which is somewhat outdated in 2024.

It would be good to have:

* Noqt
* qt5
* qt6

maybe similar to  https://github.com/conda-forge/opencv-feedstock/pull/396

**Comment by hmaarrfk** [comment]
Maybe outdated is the wrong word, but it would be beneficial to start to experiment with environments without qt5 and this is a blocker today.

**Comment by jakirkham** [comment]
Wonder if this would be better as [an issue on `nsight-compute` itself]( https://github.com/conda-forge/nsight-compute-feedstock/issues/new )

**Comment by hmaarrfk** [comment]
hmm, maybe i had a typo and i was trying to install cuda-toolkit 12 instead of cuda-version 12....

**Comment by hmaarrfk** [comment]
yes, ok my challenge was that i was trying to install cuda-toolkit 12, i should have pinned cuda-version isntead.

**Comment by hmaarrfk** [comment]
xref: https://github.com/conda-forge/nsight-compute-feedstock/issues/15

**Comment by jakirkham** [comment]
This is a little outdated and a bit rough, but maybe still helpful when thinking about the package structure

<details>

```
cuda
  ├─ cuda-runtime
  │  └─ cuda-libraries
  └─ cuda-toolkit
     ├─ cuda-compiler
     │  ├─ cuda-cuobjdump
     │  ├─ cuda-cuxxfilt
     │  ├─ cuda-nvcc
     │  └─ cuda-nvprune
     ├─ cuda-libraries
     │  ├─ cuda-cudart
     │  ├─ cuda-nvrtc
     │  ├─ cuda-opencl
     │  ├─ libcublas
     │  ├─ libcufft
     │  ├─ libcufile
     │  ├─ libcurand
     │  ├─ libcusolver
     │  ├─ libcusparse
     │  ├─ libnpp
     │  ├─ libnvjitlink
     │  └─ libnvjpeg
     ├─ cuda-libraries-dev
     │  ├─ cuda-cccl
     │  ├─ cuda-cudart-dev
     │  ├─ cuda-driver-dev
     │  ├─ cuda-nvrtc-dev
     │  ├─ cuda-opencl-dev
     │  ├─ cuda-profiler-api
     │  ├─ libcublas-dev
     │  ├─ libcufft-dev
     │  ├─ libcufile-dev
     │  ├─ libcurand-dev
     │  ├─ libcusolver-dev
     │  ├─ libcusparse-dev
     │  ├─ libnpp-dev
     │  ├─ libnvjitlink-dev
     │  └─ libnvjpeg-dev
     ├─ cuda-libraries-static
     │  ├─ cuda-cudart-static
     │  ├─ cuda-cupti-static
     │  ├─ cuda-nvrtc-static
     │  ├─ libcublas-static
     │  ├─ libcufft-static
     │  ├─ libcufile-static
     │  ├─ libcurand-static
     │  ├─ libcusolver-static
     │  ├─ libcusparse-static
     │  ├─ libnpp-static
     │  └─ libnvjpeg-static
     ├─ cuda-nvml-dev
     └─ cuda-tools
        ├─ cuda-command-line-tools
        │  ├─ cuda-cupti
        │  ├─ cuda-gdb
        │  ├─ cuda-nvdisasm
        │  ├─ cuda-nvprof
        │  ├─ cuda-nvtx
        │  └─ cuda-sanitizer-api
        ├─ cuda-visual-tools
        │  ├─ cuda-libraries-dev
        │  ├─ cuda-libraries-static
        │  ├─ cuda-nsight
        │  ├─ nsight-compute
        │  ├─ cuda-nvml-dev
        │  └─ cuda-nvvp
        │     ├─ cuda-nvdisasm
        │     └─ cuda-nvprof
        └─ gds-tools
```

</details>

**Comment by hmaarrfk** [comment]
yeah, i think that small typo caused me alot of grief....

**Comment by jakirkham** [comment]
If there are things we can do on the documentation front, would be interested to know 🙂

**Comment by hmaarrfk** [comment]
no nothing in particular.

Thanks for being so responsive!
